---

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: make sure machine directory and keys subdir exist
  file: path="{{ local_key_dir }}" state=directory follow=yes mode=0755
  delegate_to: localhost
  become: no

- name: Check to see if ssh_host_dsa_key exists
  stat: path="{{ local_key_dir }}/{{ item.file_name }}"
  delegate_to: localhost
  register: key_file
  with_items: "{{ ssh_key_config }}"
  ignore_errors: True
  become: no

- name: Generate ssh_host_dsa_key
  shell: ssh-keygen -f "{{ local_key_dir }}/{{ item.item.file_name }}" -C 'root@{{ inventory_hostname }}' -N '' -t {{ item.item.algorithm }}
  delegate_to: localhost
  with_items: "{{ key_file.results }}"
  when: not item.stat.exists
  become: no

- name: Copy SSH Host private keys
  copy: src={{ local_key_dir }}/{{ item.file_name }}
        dest={{ ssh_key_dir }}/{{ item.file_name }}
        owner=root group=root mode=0600
  with_items: "{{ ssh_key_config }}"
  notify:
    - restart sshd

- name: Copy SSH Host public keys
  copy: src={{ local_key_dir }}/{{ item.file_name }}.pub
        dest={{ ssh_key_dir }}/{{ item.file_name }}.pub
        owner=root group=root mode=0644
  with_items: "{{ ssh_key_config }}"
  notify:
    - restart sshd

- name: remove unnecessary old lines from sshd config (reduce warnings)
  lineinfile:  dest=/etc/ssh/sshd_config state=absent regexp="{{ item }}"
  with_items:
    - "^LookupClientHostnames"
    - "^VerifyReverseMapping"
    - "^MaxAuthTriesLog"
    - "^RhostsAuthentication"
    - "^RhostsRSAAuthentication"
    - "^RSAAuthentication"
    - "^ServerKeyBits"
    - "^KeyRegenerationInterval"
    - "^UsePrivilegeSeparation"
  notify:
    - restart sshd

- name: update sshd config to reduce the duration of bad connections
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    # stop bleeding listen resources
    - regexp: '^[#]?LoginGraceTime'
      line: "LoginGraceTime 8"
    # promptly send "Permission denied (publickey)." rather than prompting for an "it might be a token" password
    # if not given a key, since that is all we do here, ever."
    - regexp: '^[#]?ChallengeResponseAuthentication'
      line: "ChallengeResponseAuthentication no"
    # Following recommendations of https://github.com/arthepsy/ssh-audit as of 2020-10
    - regexp: '^[#]?kexalgorithms'
      line: "kexalgorithms {{ sshd_kex_algorithms | join(',')}}"
    - regexp: ^[#]?casignaturealgorithms
      line: "casignaturealgorithms {{ sshd_ca_sig_algorithms | join(',')}}"
    - regexp: ^[#]?hostbasedacceptedkeytypes
      line: "hostbasedacceptedkeytypes {{sshd_host_based_accepted_key_algorithms| join(',')}}"
    - regexp: ^[#]?hostkeyalgorithms
      line: "hostkeyalgorithms {{ sshd_host_key_algorithms|join(',')}}"
    - regexp: ^[#]?pubkeyacceptedkeytypes
      line: "pubkeyacceptedkeytypes {{ sshd_pubkey_accepted_key_types|join(',')}}"
    - regexp: ^[#]?macs
      line: "macs {{ sshd_mac_algorithms | join(',') }}"
    # Also, put aes256-ctr first to get aes-ni speed bump
    - regexp: ^[#]?ciphers
      line: "ciphers {{ sshd_ciphers | join(',')}}"
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'
  notify:
    - restart sshd

- name: run handlers to clear SSH if necessary
  meta: flush_handlers

- name: Verify that we can talk to the servers
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    delay: 1
    timeout: "{{ ssh_hostkey_restore_timeout }}"
    state: started
  delegate_to: "localhost"
  become: no
